// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description: string;
  content?: PortableTextBlock[];
  reading_time_minutes?: number;
  word_count?: number;
  metadata?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Doc {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  section: string;
  summary?: string;
  order: number;
  reading_time_minutes?: number;
  word_count?: number;
  metadata?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Plugin {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  tagline: string;
  headline: string;
  sub: string;
  home_card_copy: string;
  npm_package: string;
  github_url: string;
  capabilities: string;
  hooks: string;
  plugin_status: string;
  install_command: string;
  config_example?: string;
  wordpress_equivalent?: string;
  companion_component?: string;
  pairs?: string;
  pairs_note?: string;
  demo_caption: string;
  setup_note: string;
  metadata?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    blog: Post;
    docs: Doc;
    plugins: Plugin;
  }
}